# Generated by Django 4.1.6 on 2023-02-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='default_language',
            field=models.CharField(choices=[('vi', 'Viet Nam'), ('en', 'English')], max_length=200),
        ),
    ]
