# Generated by Django 4.1.6 on 2023-02-10 02:23

from django.db import migrations
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_article_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titles',
            field=jsoneditor.fields.django3_jsonfield.JSONField(blank=True, max_length=5000),
        ),
    ]
